from django.db import models
from django.utils import timezone


class Project(models.Model):
    """Main project model"""
    DIFFICULTY_CHOICES = [
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced Beginner'),
    ]
    
    TRACK_CHOICES = [
        ('frontend', 'Frontend Development'),
        ('backend', 'Backend Development'),
        ('fullstack', 'Full-Stack Development'),
        ('python', 'Python'),
        ('react', 'React'),
        ('nodejs', 'Node.js'),
    ]
    
    title = models.CharField(max_length=200)
    description = models.TextField()
    difficulty = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES)
    track = models.CharField(max_length=20, choices=TRACK_CHOICES)
    is_generated = models.BooleanField(default=False, help_text="True if this project was generated by a user")
    user_preferences = models.JSONField(default=dict, blank=True, help_text="User preferences used to generate this project (keywords, interests, etc.)")
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['difficulty', 'title']
    
    def __str__(self):
        return f"{self.title} ({self.get_difficulty_display()})"


class ProjectStep(models.Model):
    """Individual steps for a project, organized by timeframe"""
    TIMEFRAME_CHOICES = [
        ('6h', '6 Hours'),
        ('12h', '12 Hours'),
        ('24h', '24 Hours'),
        ('48h', '48 Hours'),
    ]
    
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='steps')
    step_number = models.IntegerField()
    title = models.CharField(max_length=200)
    description = models.TextField()
    technologies = models.JSONField(default=list, help_text="List of technologies introduced in this step")
    estimated_time = models.IntegerField(help_text="Estimated time in minutes")
    timeframe = models.CharField(max_length=10, choices=TIMEFRAME_CHOICES)
    learning_outcomes = models.TextField(blank=True, help_text="What the user learns in this step")
    
    class Meta:
        ordering = ['project', 'timeframe', 'step_number']
        unique_together = ['project', 'step_number', 'timeframe']
    
    def __str__(self):
        return f"{self.project.title} - Step {self.step_number} ({self.timeframe})"


class ProjectResource(models.Model):
    """Downloadable resources for projects (CSV files, sample data, etc.)"""
    RESOURCE_TYPE_CHOICES = [
        ('csv', 'CSV File'),
        ('json', 'JSON File'),
        ('txt', 'Text File'),
        ('zip', 'ZIP Archive'),
        ('other', 'Other'),
    ]
    
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='resources')
    name = models.CharField(max_length=200, help_text="Display name for the resource")
    description = models.TextField(blank=True, help_text="Brief description of what this resource contains")
    resource_type = models.CharField(max_length=10, choices=RESOURCE_TYPE_CHOICES, default='csv')
    file_path = models.CharField(max_length=500, help_text="Path to the file in static/files/ directory")
    file_size = models.CharField(max_length=20, blank=True, help_text="File size (e.g., '2.5 MB')")
    order = models.IntegerField(default=0, help_text="Display order")
    
    class Meta:
        ordering = ['project', 'order', 'name']
    
    def __str__(self):
        return f"{self.project.title} - {self.name}"


class UserSession(models.Model):
    """Track user's progress through a project (no login required)"""
    session_id = models.CharField(max_length=100, db_index=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    selected_timeframe = models.CharField(max_length=10)
    start_time = models.DateTimeField(default=timezone.now)
    current_step = models.IntegerField(default=1)
    completed_steps = models.JSONField(default=list, help_text="List of completed step numbers")
    completed = models.BooleanField(default=False)
    github_repo = models.URLField(blank=True, null=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    
    class Meta:
        ordering = ['-start_time']
        # Prevent duplicate active sessions for same project/timeframe
        constraints = [
            models.UniqueConstraint(
                fields=['session_id', 'project', 'selected_timeframe'],
                condition=models.Q(completed=False),
                name='unique_active_session'
            )
        ]
    
    def __str__(self):
        return f"Session {self.session_id[:8]}... - {self.project.title}"
    
    def get_total_steps(self):
        """Get total number of steps for selected timeframe"""
        return self.project.steps.filter(timeframe=self.selected_timeframe).count()
    
    def get_progress_percentage(self):
        """Calculate progress percentage"""
        total = self.get_total_steps()
        if total == 0:
            return 0
        return int((len(self.completed_steps) / total) * 100)
    
    def get_remaining_time(self):
        """Calculate remaining time based on timeframe"""
        elapsed = timezone.now() - self.start_time
        timeframe_hours = int(self.selected_timeframe.replace('h', ''))
        total_seconds = timeframe_hours * 3600
        remaining_seconds = total_seconds - int(elapsed.total_seconds())
        return max(0, remaining_seconds)


class UserProfile(models.Model):
    """Store user preferences and experience level (session-based, no login required)"""
    EXPERIENCE_LEVELS = [
        ('beginner', 'Complete Beginner'),
        ('some_experience', 'Some Experience'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ]
    
    session_id = models.CharField(max_length=100, unique=True, db_index=True)
    experience_level = models.CharField(max_length=20, choices=EXPERIENCE_LEVELS, blank=True)
    interested_technologies = models.JSONField(default=list, help_text="List of technologies user is interested in")
    preferred_tracks = models.JSONField(default=list, help_text="List of tracks user prefers")
    preferred_difficulty = models.CharField(max_length=20, blank=True)
    preferred_timeframe = models.CharField(max_length=10, blank=True)
    interests_keywords = models.JSONField(default=list, help_text="Keywords describing user interests")
    onboarding_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-updated_at']
    
    def __str__(self):
        return f"Profile for session {self.session_id[:8]}..."
    
    def get_recommended_projects(self, limit=6):
        """Get recommended projects based on user preferences"""
        from .models import Project
        
        queryset = Project.objects.filter(is_generated=False)  # Only pre-made projects
        
        # Filter by preferred tracks if set
        if self.preferred_tracks:
            queryset = queryset.filter(track__in=self.preferred_tracks)
        
        # Filter by preferred difficulty if set
        if self.preferred_difficulty:
            queryset = queryset.filter(difficulty=self.preferred_difficulty)
        
        # If no preferences, return all projects
        if not queryset.exists():
            queryset = Project.objects.filter(is_generated=False)
        
        return queryset[:limit]

