# Generated by Django 4.2.7 on 2025-12-15 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced Beginner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("web_dev", "Web Development"),
                            ("python", "Python"),
                            ("react", "React"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("selected_timeframe", models.CharField(max_length=10)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("current_step", models.IntegerField(default=1)),
                (
                    "completed_steps",
                    models.JSONField(
                        default=list, help_text="List of completed step numbers"
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("github_repo", models.URLField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.JSONField(
                        default=list,
                        help_text="List of technologies introduced in this step",
                    ),
                ),
                (
                    "estimated_time",
                    models.IntegerField(help_text="Estimated time in minutes"),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("6h", "6 Hours"),
                            ("12h", "12 Hours"),
                            ("24h", "24 Hours"),
                            ("48h", "48 Hours"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True, help_text="What the user learns in this step"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "timeframe", "step_number"],
                "unique_together": {("project", "step_number", "timeframe")},
            },
        ),
    ]
