# Generated by Django 4.2.7 on 2025-12-15 23:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced Beginner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend Development"),
                            ("backend", "Backend Development"),
                            ("fullstack", "Full-Stack Development"),
                            ("python", "Python"),
                            ("react", "React"),
                            ("nodejs", "Node.js"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True if this project was generated by a user",
                    ),
                ),
                (
                    "user_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences used to generate this project (keywords, interests, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["difficulty", "title"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Complete Beginner"),
                            ("some_experience", "Some Experience"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interested_technologies",
                    models.JSONField(
                        default=list,
                        help_text="List of technologies user is interested in",
                    ),
                ),
                (
                    "preferred_tracks",
                    models.JSONField(
                        default=list, help_text="List of tracks user prefers"
                    ),
                ),
                ("preferred_difficulty", models.CharField(blank=True, max_length=20)),
                ("preferred_timeframe", models.CharField(blank=True, max_length=10)),
                (
                    "interests_keywords",
                    models.JSONField(
                        default=list, help_text="Keywords describing user interests"
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("selected_timeframe", models.CharField(max_length=10)),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("current_step", models.IntegerField(default=1)),
                (
                    "completed_steps",
                    models.JSONField(
                        default=list, help_text="List of completed step numbers"
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("github_repo", models.URLField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ProjectStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.JSONField(
                        default=list,
                        help_text="List of technologies introduced in this step",
                    ),
                ),
                (
                    "estimated_time",
                    models.IntegerField(help_text="Estimated time in minutes"),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("6h", "6 Hours"),
                            ("12h", "12 Hours"),
                            ("24h", "24 Hours"),
                            ("48h", "48 Hours"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True, help_text="What the user learns in this step"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "timeframe", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="ProjectResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the resource", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of what this resource contains",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV File"),
                            ("json", "JSON File"),
                            ("txt", "Text File"),
                            ("zip", "ZIP Archive"),
                            ("other", "Other"),
                        ],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path to the file in static/files/ directory",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.CharField(
                        blank=True,
                        help_text="File size (e.g., '2.5 MB')",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed", False)),
                fields=("session_id", "project", "selected_timeframe"),
                name="unique_active_session",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectstep",
            unique_together={("project", "step_number", "timeframe")},
        ),
    ]
