# Generated by Django 4.2.7 on 2025-12-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_userprofile"),
        ("projects", "0003_usersession_unique_active_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_generated",
            field=models.BooleanField(
                default=False, help_text="True if this project was generated by a user"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="User preferences used to generate this project (keywords, interests, etc.)",
            ),
        ),
    ]
