# Generated by Django 4.2.7 on 2025-12-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_userprofile"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed", False)),
                fields=("session_id", "project", "selected_timeframe"),
                name="unique_active_session",
            ),
        ),
    ]
