# Generated by Django 4.2.7 on 2025-12-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_userprofile"),
        ("projects", "0004_usersession_unique_active_session"),
    ]

    operations = []
